name: Build and Deploy Rust API Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo registry cache
        uses: Swatinem/rust-cache@v2

      - name: Build Documentation
        run: cargo doc --no-deps --workspace --document-private-items

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: gh-pages
          force_orphan: true
